"""migration after deleted column

Revision ID: 1da898fde1eb
Revises: 8bed3476b3c3
Create Date: 2024-03-10 23:58:45.001776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da898fde1eb'
down_revision = '8bed3476b3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AppointmentDateTime', sa.DateTime(), nullable=False))
        batch_op.drop_column('AppointmentDate')
        batch_op.drop_column('AppointmentTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AppointmentTime', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('AppointmentDate', sa.DATETIME(), nullable=False))
        batch_op.drop_column('AppointmentDateTime')

    # ### end Alembic commands ###
