"""migration after adding new column

Revision ID: 8bed3476b3c3
Revises: 6baabe8b61ec
Create Date: 2024-03-09 17:34:11.453259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bed3476b3c3'
down_revision = '6baabe8b61ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AppointmentTime', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('AppointmentTime')

    # ### end Alembic commands ###
